# Generated by Django 5.0 on 2023-12-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0011_alter_searchlocation_search_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusevent',
            name='event_timestamp',
        ),
        migrations.AddField(
            model_name='campusevent',
            name='end_time',
            field=models.DateTimeField(default='2023-12-31 23:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campusevent',
            name='event_type',
            field=models.CharField(default='Other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campusevent',
            name='organizers_name',
            field=models.CharField(default='NJIT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campusevent',
            name='start_time',
            field=models.DateTimeField(default='2023-01-01 00:01'),
            preserve_default=False,
        ),
    ]
