# Generated by Django 4.2.5 on 2023-12-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0012_remove_campusevent_event_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusevent',
            name='location',
            field=models.CharField(default='Campus Center', max_length=200),
            preserve_default=False,
        ),
    ]
