# Generated by Django 4.2.5 on 2023-12-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_campusevent_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusevent',
            name='id',
        ),
        migrations.AddField(
            model_name='campusevent',
            name='event_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
