# Generated by Django 4.2.5 on 2023-12-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0014_remove_campusevent_id_campusevent_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='campusevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='campusevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='campusevent',
            name='organizers_name',
        ),
        migrations.RemoveField(
            model_name='campusevent',
            name='start_time',
        ),
    ]
