# Generated by Django 4.2.5 on 2023-12-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0017_remove_campusevent_id_campusevent_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusevent',
            name='end_time',
            field=models.DateTimeField(default='2023-12-31 23:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campusevent',
            name='event_type',
            field=models.CharField(default='Other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campusevent',
            name='location',
            field=models.CharField(default='Campus Center', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campusevent',
            name='organizers_name',
            field=models.CharField(default='NJIT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campusevent',
            name='start_time',
            field=models.DateTimeField(default='2023-01-01 01:01'),
            preserve_default=False,
        ),
    ]
