# Generated by Django 4.2.5 on 2023-12-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_rename_user_name_feedback_email_feedback_name_and_more'),
        ('navigation', '0018_campusevent_end_time_campusevent_event_type_and_more'),
    ]

    operations = [
    ]
